### PR TITLE
add new method payment with PayTabPayment

### PR DESCRIPTION
**Pull request by firasabualkomboz**

### CODE REVIEW

**Review by NafezlyDotCom — COMMENTED** [review]
please abstract (currency,paypage_lang,callback,return,customer_details.phone)
and make return with 3 returns ['payment_id','redirect_url','html']
---
also please provide verify method

**Comment by firasabualkomboz** [comment]
i am add new commit please check last updated

**Comment by firasabualkomboz** [comment]
i am providing verify method in PayTabPayment

**Comment by NafezlyDotCom** [comment]
Nice Changes , 
So Please implements this interface
https://github.com/Nafezly/payments/blob/master/src/Interfaces/PaymentInterface.php
and make the response for pay and verify like this class
https://github.com/Nafezly/payments/blob/master/src/Classes/PaymobPayment.php

**Comment by firasabualkomboz** [comment]
thanks, now I am push updated Based on the last comment , so check last updated

**Pull request merged**
